[project]
name = "llm-engineering-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.120.0",
    "bitsandbytes>=0.50.2",
    "bs4>=0.0.2",
    "datasets>=5.0.1",
    "diffusers>=0.40.0",
    "dotenv>=0.9.9",
    "google-genai>=2.14.0",
    "gradio>=6.20.0",
    "huggingface-hub>=1.25.1",
    "ipykernel>=7.3.0",
    "ipython>=9.15.0",
    "ipywidgets>=8.1.8",
    "langchain-openai>=1.4.1",
    "litellm>=1.93.0",
    "openai>=2.44.0",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "soundfile>=0.14.0",
    "tiktoken>=0.13.0",
    "torch>=2.13.0",
    "transformers>=5.15.1",
]
