[project]
name = "llm-engineering-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.120.0",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "google-genai>=2.14.0",
    "ipykernel>=7.3.0",
    "ipython>=9.15.0",
    "langchain-openai>=1.4.1",
    "litellm>=1.93.0",
    "openai>=2.44.0",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "tiktoken>=0.13.0",
]
