# now, we move to day 05, importing the required libraries
from openai import OpenAI
import os
from dotenv import load_dotenv
import json
import gradio as gr
import sqlite3
# in addition to these, we also need to import image libs, these are
import base64
from io import BytesIO
from PIL import Image
import subprocess

# now, we start by adding the boilerplate for openai and load api key

load_dotenv(override=True)
openai_key = os.getenv("OPENAI_API_KEY")
openai_client = OpenAI()

# checked open api key: okay, client is also working fine, we can proceed ahead

# now, we move ahead with image creation

# image_response = openai_client.images.generate(
#         model='gpt-image-1-mini',
#         prompt="Please create an image for New Delhi containing major tourist areas and attractions of the city, meant to be shown to a person who is planning to travel to the city.",
#         size="1024x1024"
#     )

# # now we shall get raw bytes from the LLM, we need to now convert this to raw image bytes
# image_base64 = image_response.data[0].b64_json #type: ignore
# image_data = base64.b64decode(image_base64) #type: ignore
# image = Image.open(BytesIO(image_data))
# image.show()

# image got generated, so this is working fine. We create a function to run the same.

def generate_image(city):
    image_response = openai_client.images.generate(
        model='gpt-image-1-mini',
        prompt=f"Please create an image for {city} containing major tourist areas and attractions of the {city}, meant to be shown to a person who is planning to travel to the {city}.",
        size="1024x1024"
    )

    image_base64 = image_response.data[0].b64_json #type: ignore
    image_data = base64.b64decode(image_base64) #type: ignore
    image = Image.open(BytesIO(image_data))
    return image


# now, we move to work on audio generation
# audio_response = openai_client.audio.speech.create(
#         model='gpt-4o-mini-tts-2025-12-15',
#         voice='cedar',
#         input='This is a sample text to speech sentence. This is being generated by open ai LLM'
#     )

# audio_return = audio_response.content

# with open("test.mp3", "wb") as file:
#     file.write(audio_return)

# subprocess.run(["afplay", "test.mp3"])
# this works fine, we now move to creating a function for the same

def generate_audio(message):
    audio_response = openai_client.audio.speech.create(
        model='gpt-4o-mini-tts-2025-12-15',
        voice='cedar',
        input=message
    )
    return audio_response.content


# Now, our image and audio code is ready. Now, we need to move towards defining the logic for chat
# chat must return response with pricing after running the tool, the audio for each turn or response that we received from the llm and if there's a city involved in the response and tool is being called, then the image must also be returned.
# also, since this is not the usual chat function and we shall be creating blocks, hence, message shall be passed separately using another function to the llm input

def chat(history):
    pass